### ISSUE TITLE
Docker image does not exist

### ISSUE THREAD

**Issue by goek-han** [grupozap/metrics-server-exporter#18]
https://github.com/grupozap/metrics-server-exporter/blob/aab46d80bbe0c612e6639198dc7b7b842a387289/deploy/deployment-metrics-server-exporter.yaml#L22

Error: ImagePullBackOff

Did this Image get removed? No results: https://hub.docker.com/search?q=vivareal%2Fmetrics-server-exporter&type=image

**Comment by gkope** [comment]
Hi @goek-han, I just created the tag, everything should work fine now, thanks :)

**Comment by goek-han** [comment]
Is the image on hub.docker.com? I ask because the search result is still empty:
https://hub.docker.com/search?q=vivareal%2Fmetrics-server-exporter&type=image

Sorry, if this is a noob question.

**Comment by gkope** [comment]
Hi @goek-han, can you try again? I reconfigured the permissions for this dockerhub repository 😄 .

Thanks for the reply.

**Comment by goek-han** [comment]
@gkope it works now, thanks!
