### ISSUE TITLE
How to run in Minikube?

### ISSUE THREAD

**Issue by goek-han** [grupozap/metrics-server-exporter#20]
How do I provide the following variables:

K8S_ENDPOINT - is this  minkube ip?
K8S_TOKEN - what is this in minikube?
K8S_FILEPATH_TOKEN  - what is this in minikube?

**Comment by deadc** [comment]
No need to set these variables, I've added instructions to test it on [minikube](https://github.com/grupozap/metrics-server-exporter/blob/ba349a6e426c98c31372d056cfcb8d6d7281cca0/README.md#minikube)
