### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by saiharshitachava** [grupozap/metrics-server-exporter#41]
This is very cool and useful rather than running many agent to check the usage
Do we have any grafana dashboard which are already designed to view these metrics?

**Comment by gkope** [comment]
hi @saiharshitachava :)

I'll make our dashboards public in grafana.com/dashboards and soon will paste here the link :)

**Comment by saiharshitachava** [comment]
Thanks @gkope Please tag me when u paste the link here :)

**Comment by saiharshitachava** [comment]
@gkope we dont have all these metrics as part of this exporter right?

kube_pod_container_status_restarts_total
kube_pod_container_resource_requests
kube_pod_container_resource_limits

and other metrics used..we cont have these as part of this exporter

**Comment by gkope** [comment]
you are right @saiharshitachava 

You need to configure kube-state-metrics and metrics-server + metrics-server-exporter so that the dashboard can be fully functional.

As said on the PR, the dashboards was tested by a few and it's working.
